CREATE DATABASE Security
GO



SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
USE [Security]
go

CREATE TABLE [dbo].[PERMISSION_TYPE](
    [ID] [bigint] IDENTITY(1,1) NOT NULL,
	[NAME] nvarchar(50) NOT NULL,
	[DESCRIPTION] nvarchar(50) NOT NULL,
    [CREATED_BY] [varchar](50) NOT NULL,
    [CREATED_AT] [datetime] NOT NULL CONSTRAINT [DF_PERMISSION_TYPE_CREATED_AT] DEFAULT(GETUTCDATE()),
    [UPDATED_BY] [varchar](50) NOT NULL,
    [UPDATED_AT] [datetime] NOT NULL CONSTRAINT [DF_PERMISSION_TYPE_UPDATED_AT] DEFAULT(GETUTCDATE()),
    [DELETED_AT] [datetime] NULL,
 CONSTRAINT [PK_PERMISSION_TYPE] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/*Query*/
CREATE TABLE [dbo].[PERMISSION](
    [ID] [bigint] IDENTITY(1,1) NOT NULL,
	[NAME] nvarchar(50) NOT NULL,
	[DESCRIPTION] nvarchar(50) NOT NULL,
	[PERMISSION_TYPE_ID] bigint not null CONSTRAINT FK_PERMISSION_TYPE REFERENCES PERMISSION_TYPE(ID) ,
    [CREATED_BY] [varchar](50) NOT NULL,
    [CREATED_AT] [datetime] NOT NULL CONSTRAINT [DF_PERMISSION_CREATED_AT] DEFAULT(GETUTCDATE()),
    [UPDATED_BY] [varchar](50) NOT NULL,
    [UPDATED_AT] [datetime] NOT NULL CONSTRAINT [DF_PERMISSION_UPDATED_AT] DEFAULT(GETUTCDATE()),
    [DELETED_AT] [datetime] NULL,
 CONSTRAINT [PK_PERMISSION] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

